/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    GameView: typeof import('./src/components/game/GameView.vue')['default']
    GameViewGoals: typeof import('./src/components/game/GameViewGoals.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StandingsTeam: typeof import('./src/components/StandingsTeam.vue')['default']
    StandingsView: typeof import('./src/components/StandingsView.vue')['default']
    TeamScheduleGame: typeof import('./src/components/TeamScheduleGame.vue')['default']
    TeamScheduleView: typeof import('./src/components/TeamScheduleView.vue')['default']
  }
}
